import Head from "next/head";
import SideBar from "../components/SideBar";
import { auth } from "../firebase";

export default function Home() {
  // auth.signOut();
  return (
    <div>
      <Head>
        <title>WhatsApp</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <SideBar />
    </div>
  );
}
