import Head from "next/head";
import SideBar from "../components/SideBar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>WhatsApp</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <SideBar />
    </div>
  );
}
